stages:
  - test
  - package

build:
  stage: package
  image:
    name: python:3.9
  script:
    # Install dependencies
    - apt-get update && apt-get install -y curl
    - python3 -m pip install --no-cache-dir .
    # Build with pyinstaller
    - pyinstaller --onefile --clean --windowed datario_cli/cli.py
    # Ensure it works
    - dist/cli --help
    # Rename it for better packaging
    - mv dist/cli datario-linux-x64
    # Upload artifact
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file datario-linux-x64 "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/datario/stable/datario-linux-x64"'


