stages:
  - test
  - package

build:
  stage: package
  image:
    name: python:3.9-slim
  script:
    # Install dependencies
    - sudo apt-get update && sudo apt-get install -y curl
    - python3 -m pip install --no-cache-dir .
    # Build with pyinstaller
    - pyinstaller --onefile --clean --windowed datario_cli/cli.py
    # Ensure it works
    - dist/datario_cli --help
    # Rename it for better packaging
    - mv dist/datario_cli datario-linux-x64
    # Upload artifact
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --upload-file "datario-linux-x64" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/datario/stable"


