name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: datario_cli/cli.py

    - uses: actions/upload-artifact@v2
      with:
        name: datario-cli-linux
        path: dist/cli
