name: Release edrio

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: ${{ matrix.os }} - build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build
        run: |
          pyinstaller --onefile --clean --windowed edrio.py

      - name: Ensure it works
        run: |
          dist/edrio --help

      - name: Move it to current directory
        run: |
          mv dist/edrio ./edrio-${{ github.ref_name }}-${{ matrix.os }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: uploads
          path: ./edrio-${{ github.ref_name }}-${{ matrix.os }}

  upload-release:
    runs-on: ubuntu-18.04
    needs:
      - build

    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: uploads

      - run: |
          set -x
          assets=()
          for asset in ./uploads/*; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
